// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8IB8eE1sJpeWi-tRQc3JEVKUGSmbfoZk',
    appId: '1:707575885666:ios:ef3f373ece1af1521e463b',
    messagingSenderId: '707575885666',
    projectId: 'domain-visualiser-app',
    storageBucket: 'domain-visualiser-app.firebasestorage.app',
    iosBundleId: 'co.enspyr.domainVisualiser',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp39f2SodShtfjeimqb0Wmrl5udkMLo8Y',
    appId: '1:707575885666:web:af5eddfec54849191e463b',
    messagingSenderId: '707575885666',
    projectId: 'domain-visualiser-app',
    authDomain: 'domain-visualiser-app.firebaseapp.com',
    storageBucket: 'domain-visualiser-app.firebasestorage.app',
  );

}